prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn-sc1
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi

kube-state-metrics:
  enabled: true

grafana:
  adminPassword: "test-password-5454!"
  persistence:
    enabled: true
    storageClassName: longhorn-sc1
    accessModes: ["ReadWriteOnce"]
    size: 1Gi

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn-sc1
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi