apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-conf
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  project: default

  source:
    repoURL: https://your-git-repo.com/your-repo
    targetRevision: HEAD
    path: longhorn/

  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true