apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-infr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/CuteAnimeGirl/agrocd-studying.git
    targetRevision: master
    path: infra/applications

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true