apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-pvc
  namespace: gitlab
  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-sc1
  resources:
    requests:
      storage: 16Gi