apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-conf
  namespace: argocd
  finalizers:
    - finalizer.argocd.argoproj.io/resources
  annotations:
    argocd.argoproj.io/sync-wave: "-5"

spec:
  project: default

  source:
    repoURL: 'https://github.com/CuteAnimeGirl/argocd-studying.git'
    targetRevision: master
    path: infra/argocd/

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true