apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-internal-helm
  namespace: argocd
  finalizers:
    - finalizer.argocd.argoproj.io/resources
  annotations:
    argocd.argoproj.io/sync-wave: "-10"

spec:
  project: default
  
  sources:
  - repoURL: 'https://kubernetes.github.io/ingress-nginx'
    chart: ingress-nginx
    targetRevision: 4.13.2
    helm:
      valueFiles:
      - $values/infra/helm/ingr-nginx-int-values.yaml

  - repoURL: 'https://github.com/CuteAnimeGirl/argocd-studying.git'
    targetRevision: master
    ref: values
  
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx-internal
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true