apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-external-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  
  sources:
  - repoURL: 'https://kubernetes.github.io/ingress-nginx'
    chart: ingress-nginx
    targetRevision: 4.13.2
    helm:
      valueFiles:
      - $values/infra/helm/ingr-nginx-ext-values.yaml

  - repoURL: 'https://github.com/CuteAnimeGirl/agrocd-studying.git'
    targetRevision: master
    ref: values
  
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx-external
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true