apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-helm
  namespace: argocd
  finalizers:
    - finalizer.argocd.argoproj.io/resources
  annotations:
    argocd.argoproj.io/sync-wave: "-10"

spec:
  project: default
  
  sources:
  - repoURL: 'https://charts.longhorn.io'
    chart: longhorn
    targetRevision: 1.9.1
    helm:
      valueFiles:
      - $values/infra/helm/longhorn-values.yaml

  - repoURL: 'https://github.com/CuteAnimeGirl/argocd-studying.git'
    targetRevision: master
    ref: values
  
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true