apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-conf
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: 'https://github.com/CuteAnimeGirl/agrocd-studying.git'
    targetRevision: master
    path: infra/longhorn/

  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true