apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-conf
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: 'https://github.com/CuteAnimeGirl/argocd-studying.git'
    targetRevision: master
    path: apps/gitlab/

  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true