apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  
  sources:
  - repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 77.11.0
    helm:
      valueFiles:
      - $values/apps/helm/monitoring-values-sec.yaml
      - $values/apps/helm/monitoring-values.yaml

  - repoURL: 'https://github.com/CuteAnimeGirl/argocd-studying.git'
    targetRevision: master
    ref: values
  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true