apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-internal-helm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"

spec:
  project: default
  
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.13.2
    chart: ingress-nginx
    helm:
      valueFiles:
        - ingr-nginx-int-values.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx-internal
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true